local entity = {}
entity = {}
entity["arcana"] = [[Justice]]
entity["spellDeck"] = {}
entity["spellDeck"][1] = [[Mahamaon]]
entity["spellDeck"][2] = [[]]
entity["spellDeck"][3] = [[Masukukaja]]
entity["spellDeck"][4] = [[]]
entity["spellDeck"][5] = [[Hama Boost]]
entity["spellDeck"][6] = [[]]
entity["desc"] = [[Cherubim have four faces: one of each a man, an ox, a lion, and an eagle. They have four conjoined wings covered with eyes, a lion's body figure, and they have ox's feet. Cherubim guard the way to the tree of life in the Garden of Eden and the throne of God. Modern usage has blurred the distinction between cherubim and putti, the winged human baby/toddler-like beings traditionally used in figurative art.]]
entity["heritage"] = {}
entity["heritage"][1] = [[Light]]
entity["heritage"][2] = [[Slash]]
entity["spellLearn"] = {}
entity["spellLearn"]["Fatal End"] = [[58]]
entity["spellLearn"]["Mediarahan"] = [[56]]
entity["spellLearn"]["Repel Light"] = [[59]]
entity["stats"] = {}
entity["stats"][1] = [[38]]
entity["stats"][2] = [[34]]
entity["stats"][3] = [[27]]
entity["stats"][4] = [[36]]
entity["stats"][5] = [[33]]
entity["level"] = [[55]]
entity["resistance"] = {}
entity["resistance"][1] = [[Normal]]
entity["resistance"][2] = [[Normal]]
entity["resistance"][3] = [[Normal]]
entity["resistance"][4] = [[Null]]
entity["resistance"][5] = [[Normal]]
entity["resistance"][6] = [[Normal]]
entity["resistance"][7] = [[Normal]]
entity["resistance"][8] = [[Null]]
entity["resistance"][9] = [[Weak]]
entity["name"] = [[Cherub]]
return entity
